app:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 384Mi
  host: jardinmental.fabrique.social.gouv.fr
  redirectFrom:
    - jardinmental.fr
    - monsuivipsy.fr
    - monsuivipsy.fabrique.social.gouv.fr
